#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


# ❌ Check for current prebuild status
if [ ! -f .prebuild-complete ]; then
  echo "❌ You must run 'npm run pre-build' before pushing."
  exit 1
fi

# ❌ Delete the old .prebuild-complete file if it exists
if [ -f .prebuild-complete ]; then
  rm .prebuild-complete
  echo "🧹 Removed outdated .prebuild-complete"
fi

echo "✅ Pre-build check passed"
